add p10/12x
alma/AlmaSyliusPaymentPlugin pull request #12
Opened 2023-08-25 12:44 UTC by Benjamin-Freoua-Alma

### Reason for change

[add p10/12x](https://linear.app/almapay/issue/MPP-555/add-p1012x)

### Code changes

Add 10 and 12 installment in select form

### How to test

Create and pay with 10 and 12 installment

### Checklist for authors and reviewers

- [ ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [ ] The PR implements the changes asked in the referenced task / issue
- [ ] You understand the impact of this PR on existing code/features

### Non applicable

- [ ] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [ ] The tests are relevant, and cover the corner/error cases, not only the happy path
- [ ] The changes include adequate logging and Datadog traces
- [ ] Documentation is updated (API, developer documentation, ADR, Notion...)

2023-08-30 20:51 UTC, Francois-Gomis reviewed
Need frontend design for credit fees.

2023-09-06 07:25 UTC, ClaireAlma requested changes

2023-09-06 07:25 UTC, ClaireAlma commented on src/Controller/InstallmentPlanController.php
> +final class InstallmentPlanController
mettre un commentaire de classe

2023-09-06 07:25 UTC, ClaireAlma commented on src/Controller/InstallmentPlanController.php
> +    private Environment $twig;
mettre les commentaires des variables de classe

2023-09-06 07:25 UTC, ClaireAlma commented on src/Controller/InstallmentPlanController.php
> +    public function __construct(
Manque le commentaire de fonction

2023-09-06 07:25 UTC, ClaireAlma commented on src/Controller/InstallmentPlanController.php
> +    public function renderPaymentPageInstallmentPlanAction(Request $request): Response
commentaire de fonction

2023-09-06 07:25 UTC, ClaireAlma commented on src/Controller/InstallmentPlanController.php
> +        try {
remontrer le try pour englober le debut du code dans la fonction

2023-09-06 07:25 UTC, ClaireAlma commented on src/Controller/InstallmentPlanController.php
> +            return new Response('');
logger les exceptions,et dans un controller on doit catcher tous les types d'exception possible pas que InvalidArgumentException

2023-09-06 07:25 UTC, ClaireAlma commented on src/Form/Type/SelectPaymentType.php
> +final class SelectPaymentType extends AbstractResourceType
manque commentaires de class et fonction

2023-09-06 07:25 UTC, ClaireAlma commented on src/Form/Type/SelectPaymentType.php
> +        return 'sylius_checkout_select_payment';
passer cette chaine de caractere en constante

2023-09-06 07:34 UTC, ClaireAlma commented
@Benjamin-Freoua-Alma Miss the changelog informations

2023-09-18 09:24 UTC, joyet-simon commented on src/Controller/InstallmentsController.php
> +use Alma\SyliusPaymentPlugin\Bridge\AlmaBridgeInterface;
This import is unused

2023-09-18 12:13 UTC, joyet-simon commented on src/Resources/views/_partials/_javascript.html.twig
> +ClaireTest
To remove

2023-09-18 12:16 UTC, joyet-simon commented on src/Resources/views/_partials/_almaPnxPlus4.html.twig
Maybe rename to _almaCredit.html.twig

2023-09-18 12:16 UTC, joyet-simon commented on src/Resources/public/js/alma.js
> +        console.log('click click !!!!');
Remove console logs

2023-09-18 12:19 UTC, joyet-simon approved these changes

2023-09-18 12:40 UTC, ClaireAlma commented
@joyet-simon tu as tester ? on ne valide plus les PR si on ne les testes pas ou sinon on écrit en commentaire, review ok mais non testée. Merci

2023-09-18 13:18 UTC, ClaireAlma commented on src/Resources/views/bundles/SyliusShopBundle/Checkout/SelectPayment/_choiceAlma.html.twig
> +            <img src="{{ asset('/bundles/almasyliuspaymentplugin/img/p' ~ method.gatewayConfig.config.installments_count ~ 'x_logo.svg') }}" class="ui center aligned inline image" alt="Logo Alma" />
Alma logo is not translated

2023-09-18 13:19 UTC, ClaireAlma approved these changes

2023-09-19 07:45 UTC, ClaireAlma commented on composer.json
> +    "alma/alma-php-client": ">=1.11.1",
il faudra pas oublier de mettre la version du PHP client

2023-09-20 07:11 UTC, Francois-Gomis approved these changes

2023-09-20 07:11 UTC, Francois-Gomis commented on src/Helper/EligibilityHelper.php
> +
you can split data builder and eligibility call

2023-09-20 07:11 UTC, Francois-Gomis commented on src/Resources/translations/flashes.de.yml
> +alma_sylius_payment_plugin:
No deepl translation ?

2023-09-20 11:49 UTC, Benjamin-Freoua-Alma commented on src/Helper/EligibilityHelper.php
> +
@Francois-Gomis 
I added the eligibilityDataBuilder :)

2023-09-21 10:09 UTC, merged