Feature/ecom 1822 sylius add hmac verification on ipn
alma/AlmaSyliusPaymentPlugin pull request #18
Opened 2024-09-30 12:53 UTC by joyet-simon

### Reason for change

[Linear task](https://linear.app/almapay/issue/ECOM-1822/[-sylius]-add-hmac-verification-on-ipn)
 Need to implement HMAC verification for IPN

### Code changes

We add a SecurityHelper, a new AlmaException and a SecurityException.
In the SecurityHelper, we use the php client's function to make a verification on the signature.
We call this helper's function in the notify action (=IPN) and we throw exception when it's necessary.  

### How to test

_As a reviewer, you are encouraged to test the PR locally._

Try to make a payment on the [QA ENV](https://hmac-qa-sylius-1-11-4.integrations.getalma.eu/fr_FR/), leave the Alma checkout before the return on the success page to get IPN call. Check on Datadog if everything is fine.
You can use POSTMAN to make a call with no signature or a bad signature.

### Checklist for authors and reviewers

- [ ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [ ] The PR implements the changes asked in the referenced task / issue
- [ ] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [ ] The tests are relevant, and cover the corner/error cases, not only the happy path
- [ ] You understand the impact of this PR on existing code/features
- [ ] The changes include adequate logging and Datadog traces
- [ ] Documentation is updated (API, developer documentation, ADR, Notion...)

### Non applicable

2024-09-30 12:56 UTC, FranceBe commented on .github/workflows/aqua.yml
> +name: Aqua
this does not look like part of the initial ticket ? is there a reason to include those change in this PR ? :o

2024-09-30 12:59 UTC, joyet-simon commented on .github/workflows/aqua.yml
> +name: Aqua
Yes, I was just because I make a mistake on the base branch for the pr

2024-10-03 14:35 UTC, Benjamin-Freoua-Alma requested changes

2024-10-03 14:35 UTC, Benjamin-Freoua-Alma commented on src/Helper/SecurityHelper.php
> +			 throw new SecurityException("HMAC validation failed for payment $paymentId");
I think we can add the api_key and signature in the message throwed. WDYT ?

2024-10-03 14:35 UTC, Benjamin-Freoua-Alma commented on src/Payum/Action/NotifyAction.php
> +			$this->securityHelper->isHmacValidated(
The HMAC verification didn't work, I think we need to explore how does work the NotifyAction and tokenFactory

2024-10-03 14:35 UTC, Benjamin-Freoua-Alma commented on src/Payum/Action/NotifyAction.php
> +			$this->securityHelper->isHmacValidated(
<img width="854" alt="Capture d’écran 2024-10-03 à 16 34 44" src="https://github.com/user-attachments/assets/bfc88111-6457-4ecd-9a08-9f60d964eb1a">

2024-10-04 07:07 UTC, joyet-simon commented on src/Helper/SecurityHelper.php
> +			 throw new SecurityException("HMAC validation failed for payment $paymentId");
Done

2024-10-07 07:26 UTC, Francois-Gomis requested changes

2024-10-07 07:26 UTC, Francois-Gomis commented on src/Helper/SecurityHelper.php
> +			 throw new SecurityException("HMAC validation failed for payment $paymentId - API key: $key, signature: $signature");
Warning  : Leak API KEY !!!!

2024-10-07 07:29 UTC, joyet-simon commented on src/Helper/SecurityHelper.php
> +			 throw new SecurityException("HMAC validation failed for payment $paymentId - API key: $key, signature: $signature");
Done

2024-10-07 07:59 UTC, Francois-Gomis requested changes

2024-10-07 07:59 UTC, Francois-Gomis commented on src/Helper/SecurityHelper.php
> +		$this->paymentValidator = new PaymentValidator();
Ad Injection dependency, i think autowiring is enable !

2024-10-08 15:35 UTC, Benjamin-Freoua-Alma approved these changes
Without QA Test

2024-10-22 07:49 UTC, closed without merging